### ISSUE TITLE
CPU is better than GPU ?

### ISSUE THREAD

**Issue by jamessmith90** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#102]
I am completely confused.

Q1. How can setting device CPU give better output than GPU in the run_video_face_detect_onnx.py file ?

Q2. Can i use this model to train on multiple classes ?

Thanks.

**Comment by Linzaer** [comment]
A1.Do you mean the result is not correct running in GPU mode？The results of both should be the same.If you mean  running slow in gpu mode, you need to install and use onnxruntime-gpu package instead of onnxruntime package.
A2.Yes, but you need to modify the detection header  of the network , the anchor policy, and the pre-training process.

**Comment by jamessmith90** [comment]
I want to train your Detector for pedestrian and vehicle detection. 
Person, Cycle, Motorcycle, Car, Truck, Bus : 6 classes

Can you tell me what changes i need to make in the network in order to train for such a scenario ?

**Comment by Linzaer** [comment]
The response above illustrates several areas that need to be modified and multi-class implementation can refer to the default [ssd](https://github.com/qfgaohao/pytorch-ssd).
