### ISSUE TITLE
Can it changed into support 2 classes or more to train?

### ISSUE THREAD

**Issue by jinfagang** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#37]
Except face, what if adding one more class for training, does it possible to change?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/67157363-ace97580-f35d-11e9-88e7-c049c85eee71.png)

Not always but sometime detected hands as faces. I am concerned the model structure ability to aware features except of color space.

**Comment by Linzaer** [comment]
Hi,@jinfagang 
1. You have to modify the code, including modify anchor and other image preprocessing processes to match your own  data better.You also have to  make your own data set to train.
2.  Since the model backbone is too lightweight, there may be some false detections in specific areas.You can try increasing the threshold or reducing the input size.
