### ISSUE TITLE
用于轻量级行人检测

### ISSUE THREAD

**Issue by chenhuanan** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#65]
@Linzaer 请教一下，我正准备再此基础上训练一个行人检测器，不知道您之前是否有做过这方面的尝试，效果怎样？谢谢

**Comment by Linzaer** [comment]
调整下anchor比例和大小，还有预处理流程里的crop、expand策略，效果应该还可以。

**Comment by DuckJ** [comment]
请问你试了行人检测么？ @chenhuanan 
[https://github.com/songwsx/RFSong-779](https://github.com/songwsx/RFSong-779)请问这个模型跟作者你这个比在arm上速度谁的会快点哈，知道么 @Linzaer

**Comment by Linzaer** [comment]
@DuckJ 具体没跑过哈，不过看计算量的话应该差不多，不过他的这个模型主要是基于vgg改的，所包含不少可以被winograd卷积加速的通用卷积，所以在加速推理框架下的加速效果可能更好一点。

**Comment by DuckJ** [comment]
@Linzaer 谢谢你。

**Comment by chenhuanan** [comment]
> 请问你试了行人检测么？ @chenhuanan
> https://github.com/songwsx/RFSong-779请问这个模型跟作者你这个比在arm上速度谁的会快点哈，知道么 @Linzaer
训练效果挺好，RFSong要快一丢丢

**Comment by DuckJ** [comment]
arm上RFSong快一点点么？------------------ 原始邮件 ------------------
发件人: "chenhuanan"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 下午3:53
收件人: "Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com>;
抄送: "ZJ"<jin_zhang@duckj.cn>;"Mention"<mention@noreply.github.com>;
主题: Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65)


 
请问你试了行人检测么？ @chenhuanan
 https://github.com/songwsx/RFSong-779请问这个模型跟作者你这个比在arm上速度谁的会快点&#x54C8;，知道么 @Linzaer
 训练效果挺好，RFSong要快一丢丢
  
&mdash;

**Comment by chenhuanan** [comment]
arm上没试过，速度差别不大，RFsong的prior box要多些，light Face这个我还没训练完毕




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ZJ"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 下午4:41
收件人:&nbsp;"Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com&gt;;
抄送:&nbsp;"陈华楠"<947657558@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65)



arm上RFSong快一点点么？------------------ 原始邮件 ------------------ 
 发件人: "chenhuanan"<notifications@github.com&gt; 
 发送时间: 2019年11月29日(星期五) 下午3:53 
 收件人: "Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com&gt;; 
 抄送: "ZJ"<jin_zhang@duckj.cn&gt;;"Mention"<mention@noreply.github.com&gt;; 
 主题: Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65) 
 
 
   
 请问你试了行人检测么？ @chenhuanan 
  https://github.com/songwsx/RFSong-779请问这个模型跟作者你这个比在arm上速度谁的会快点&amp;#x54C8;，知道么 @Linzaer 
  训练效果挺好，RFSong要快一丢丢 
    
 &amp;mdash;

**Comment by DuckJ** [comment]
我在人脸这个训练行人，map只能到62多点，兄弟到多少了，欢迎分享哈。我测了song的flops，3G多貌似，人脸这个100多M------------------ 原始邮件 ------------------
发件人: "chenhuanan"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 下午5:02
收件人: "Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com>;
抄送: "ZJ"<jin_zhang@duckj.cn>;"Mention"<mention@noreply.github.com>;
主题: Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65)


arm上没试过，速度差别不大，RFsong的prior box要多些，light Face这个我还没训练完毕 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"ZJ"<notifications@github.com&gt;; 
 发送时间:&nbsp;2019年11月29日(星期五) 下午4:41 
 收&#x4EF6;人:&nbsp;"Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com&gt;; 
 抄送:&nbsp;"陈华楠"<947657558@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 
 主题:&nbsp;Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65) 
 
 
 
 arm上RFSong快一点点么？------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "chenhuanan"<notifications@github.com&gt;  
  发送时间: 2019年11月29日(星期五) 下午3:53  
  收&#x4EF6;人: "Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com&gt;;  
  抄送: "ZJ"<jin_zhang@duckj.cn&gt;;"Mention"<mention@noreply.github.com&gt;;  
  主题: Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65)  
   
   
     
  请问你试了行人检测么？ @chenhuanan  
   https://github.com/songwsx/RFSong-779请问这个模型跟作者你这个比在arm上速度谁的会快点&amp;#x54C8;，知道么 @Linzaer  
   训练效果挺好，RFSong要快一丢丢  
      
  &amp;mdash;  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you were mentioned. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by Linzaer** [comment]
@DuckJ 有修改anchor策略和图片预处理流程吗？

**Comment by DuckJ** [comment]
anchor策略参考RFSong的那个，预处理跟他也一样的，resize300 300的。请问能给点意见么------------------ 原始邮件 ------------------
发件人: "linzai"<notifications@github.com>
发送时间: 2019年11月29日(星期五) 晚上9:02
收件人: "Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB"<Ultra-Light-Fast-Generic-Face-Detector-1MB@noreply.github.com>;
抄送: "ZJ"<jin_zhang@duckj.cn>;"Mention"<mention@noreply.github.com>;
主题: Re: [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB] 用于轻量级行人检测 (#65)



@DuckJ 有修改anchor策略和图片预处理流程吗？
 
&mdash;

**Comment by Linzaer** [comment]
人脸这个的网络计算量和参数都要小不少，所以主干性能会低一点。尝试调整下lr策略试试吧。
